import type { Metadata } from "next";
import { Flavors, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/Theme/ThemeProvider";
import ThemeWrapper from "./components/Theme/ThemeWrapper";




const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Codescience",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          enableColorScheme
          themes={["dark", "light"]}
        >
          <ThemeWrapper>
            {children}
          </ThemeWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
